-- Generated by CSharp.lua Compiler
local System = System
local UnityEditor = UnityEditor
local UnityEngine = UnityEngine
System.namespace("CSharpLua", function (namespace)
end)
System.namespace("", function (namespace)
  namespace.class("TestUtils2", function (namespace)
    local Load
    Load = function (path)
      local prefab = System.cast(UnityEngine.GameObject, UnityEditor.AssetDatabase.LoadMainAssetAtPath(path))
      return prefab
    end
    return {
      Load = Load
    }
  end)
end)
